CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar NOT NULL
);

CREATE TABLE "events" (
  "id" uuid PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "start_date" timestamp NOT NULL,
  "end_date" timestamp NOT NULL,
  "capacity" int NOT NULL,
  "current_count" int NOT NULL DEFAULT 0,
  "status" varchar NOT NULL,
  "category_id" bigint NOT NULL,
  "address_id" uuid NOT NULL
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "addresses" (
  "id" uuid PRIMARY KEY,
  "street" varchar NOT NULL,
  "city" varchar NOT NULL,
  "state" varchar NOT NULL
);

CREATE TABLE "registrations" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "event_id" uuid NOT NULL,
  "status" varchar NOT NULL
);

CREATE TABLE "event_organizers" (
  "event_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  PRIMARY KEY ("event_id", "user_id")
);

ALTER TABLE "events" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "addresses" ADD FOREIGN KEY ("id") REFERENCES "events" ("address_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "registrations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "registrations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_organizers" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_organizers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
